APP_NAME = 'businessservice'

LOGGLY_ENABLED = False

POSTGRES_DB_NAME = 'postgres'
POSTGRES_DB_HOST = 'localhost'
POSTGRES_DB_PASS = '123123'
POSTGRES_DB_PORT = 5432
POSTGRES_DB_USER = 'postgres'

KIOSK_HEALTH_CHECK_GRACE_PERIOD = 10